### ISSUE TITLE
I can't figure out Amp ENV

### ISSUE THREAD

**Issue by SephReed** [zynaddsubfx/user-manual#20]
Why is my attack not slow?  I shows little dots moving slowly upwards, but I hear nothing.

<img width="1172" alt="Screen Shot 2020-01-27 at 12 18 46 PM" src="https://user-images.githubusercontent.com/14002040/73201693-32b85200-40ff-11ea-86d0-15117153e1df.png">

**Comment by fundamental** [comment]
On 01-27, Seph Reed wrote:
> Why is my attack not slow?  I shows little dots moving slowly upwards, but I hear nothing.

It looks like you have pad synth and add synth enabled. The envelope is
tied to only one engine, so I'm guessing you're hearing something from
the other engine.

**Comment by SephReed** [comment]
Thank you.
