### ISSUE TITLE
What is :icons: font?

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/user-manual#4]
![image](https://user-images.githubusercontent.com/491704/39864113-f079118a-5448-11e8-87ee-9fddc8a02066.png)

I've found this statement in the `Manual.adoc` file and I can't figure out what it is for. Can someone enlighten me?

**Comment by fundamental** [comment]
That's to enable icons for TIP, NOTE, IMPORTANT, WARNING, CAUTION. e.g. the lightbulb that can be seen at http://asciidoctor.org/docs/

**Comment by unfa** [comment]
I see, thanks! is `:icons:` a keyword and `fonts` a name of an icon set?

**Comment by fundamental** [comment]
Yep, more or less.
Asciidoc has a number of different properties that you can set
(e.g. the current admonition icons set).
